# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RunProgress(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RunProgress()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRunProgress(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RunProgress
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RunProgress
    def RunId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def Phase(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def Severity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RunProgress
    def Pct(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RunProgress
    def Detail(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RunProgressStart(builder):
    builder.StartObject(6)

def Start(builder):
    RunProgressStart(builder)

def RunProgressAddRunId(builder, runId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(runId), 0)

def AddRunId(builder, runId):
    RunProgressAddRunId(builder, runId)

def RunProgressAddPhase(builder, phase):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(phase), 0)

def AddPhase(builder, phase):
    RunProgressAddPhase(builder, phase)

def RunProgressAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    RunProgressAddMessage(builder, message)

def RunProgressAddSeverity(builder, severity):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(severity), 0)

def AddSeverity(builder, severity):
    RunProgressAddSeverity(builder, severity)

def RunProgressAddPct(builder, pct):
    builder.PrependInt32Slot(4, pct, 0)

def AddPct(builder, pct):
    RunProgressAddPct(builder, pct)

def RunProgressAddDetail(builder, detail):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(detail), 0)

def AddDetail(builder, detail):
    RunProgressAddDetail(builder, detail)

def RunProgressEnd(builder):
    return builder.EndObject()

def End(builder):
    return RunProgressEnd(builder)
