/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kungfu_Context */

#ifndef _Included_com_kungfu_Context
#define _Included_com_kungfu_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kungfu_Context
 * Method:    nativeNew
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_kungfu_Context_nativeNew
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_kungfu_Context
 * Method:    add_account
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_kungfu_Context_add_1account
  (JNIEnv *, jobject, jstring, jstring, jdouble);

/*
 * Class:     com_kungfu_Context
 * Method:    subscribe
 * Signature: (Ljava/lang/String;Ljava/util/ArrayList;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kungfu_Context_subscribe
  (JNIEnv *, jobject, jstring, jobject, jstring);

/*
 * Class:     com_kungfu_Context
 * Method:    insert_order
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;DJLcom/kungfu/PriceType;Lcom/kungfu/Side;Lcom/kungfu/Offset;Lcom/kungfu/HedgeFlag;)J
 */
JNIEXPORT jlong JNICALL Java_com_kungfu_Context_insert_1order
  (JNIEnv *, jobject, jstring, jstring, jstring, jdouble, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     com_kungfu_Context
 * Method:    cancel_order
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_kungfu_Context_cancel_1order
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_kungfu_Context
 * Method:    req_history_order
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kungfu_Context_req_1history_1order
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_kungfu_Context
 * Method:    req_history_trade
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kungfu_Context_req_1history_1trade
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
