/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kungfu_Runner */

#ifndef _Included_com_kungfu_Runner
#define _Included_com_kungfu_Runner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kungfu_Runner
 * Method:    init
 * Signature: (Lcom/kungfu/Runner;)V
 */
JNIEXPORT void JNICALL Java_com_kungfu_Runner_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_kungfu_Runner
 * Method:    run
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_kungfu_Runner_run
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
