# SPDX-License-Identifier: Apache-2.0

name: Source Acceptance

on:
  pull_request:
    branches:
      - dev/v*/v*

permissions:
  contents: read

jobs:
  source-acceptance:
    name: Source acceptance
    uses: kungfu-systems/buildchain/.github/workflows/check.yml@52dba6d30051b53d6f6b723fa6e27b090ce4311f # v2.12.7
    with:
      buildchain-ref: v2
      mode: source
      upload-artifacts: true
